routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/verifyemail/{token}', 'Auth\RegisterController@verify');


Route::get('fire', function () {
    // this fires the event
    event(new App\Events\MapAccess());
    return "event fired";
});

Route::get('test', function () {
    // this checks for the event
    return view('test');
});

/*
|--------------------------------------------------------------------------
| Admin Panel Routes
|--------------------------------------------------------------------------
| These routes manage access to the admin panel. 
|  
*/

Route::get('/admin', 'AdminPanelController@index')->name('admin')->middleware(['auth', 'admin']);

Route::get('/admin/dashboard', 'AdminPanelController@dashboard')->name('admin.dashboard')->middleware(['auth', 'ajax', 'admin']);

Route::resource('users', 'UserController', ['except', [
    'show'
]])->middleware(['auth', 'ajax', 'admin', 'manageUsers']);

Route::resource('roles', 'RoleController', ['except', [
    'show'
]])->middleware(['auth', 'ajax', 'admin', 'manageUsers']);

Route::resource('permissions', 'PermissionController', ['except', [
    'show'
]])->middleware(['auth', 'ajax', 'admin', 'manageUsers']);

Route::resource('terminals', 'TerminalController', ['except', [
    'show'
]])->middleware(['auth', 'ajax', 'admin', 'terminalAdmin']);

Route::get('terminals/edituser/{id}', 'TerminalController@editUser')->name('terminals.editUser')->middleware(['auth', 'ajax']);

Route::post('terminals/updateuser/{id}', 'TerminalController@updateUser')->name('terminals.updateUser')->middleware(['auth', 'ajax']);

Route::resource('terminalconfigs', 'TerminalConfigurationController')->middleware(['auth', 'ajax']);


/*
|--------------------------------------------------------------------------
| My Account Panel Routes
|--------------------------------------------------------------------------
| These routes manage access to the my account panel. 
|  
*/

Route::resource('myaccount', 'MyAccountController', ['only', [
    'index','create', 'store'
]])->middleware(['auth', 'ajax']);

/*
|--------------------------------------------------------------------------
| Home Panel Routes
|--------------------------------------------------------------------------
| These routes manage access to the home panel. 
|  
*/

Route::get('/home', 'HomeController@index')->name('home')->middleware(['auth']);

Route::get('/home/dashboard', 'HomeController@dashboard')->name('home.dashboard')->middleware(['auth', 'ajax', 'admin']);


Route::resource('userterminals', 'UserTerminalsController', ['only', [
    'index','edit','update'
]])->middleware(['auth', 'ajax', 'terminalManage']);

Route::resource('terminalgroups', 'TerminalGroupController', ['except', [
    'show'
]])->middleware(['auth', 'ajax', 'terminalManage']);

Route::resource('drivers', 'DriverController', ['except', [
    'show'
]]);


/**
 * Reports subsection routes
 * This is meant for the reports subsection of home
 */

Route::get('/home/reports', 'ReportController@index')->name('reports')->middleware(['auth','reports']);

Route::get('/home/reports/dashboard', 'ReportController@dashboard')->name('reports.dashboard')->middleware(['auth', 'ajax', 'reports']);

Route::post('home/reports/export', 'ReportController@export')->name('exportreport')->middleware(['auth', 'reports']);

Route::resource('/home/reports/terminalperformance', 'TerminalPerformanceReportController', ['names' => [
    'index' => 'terminalperformance.index',
    'create' => 'terminalperformance.create',
    'store' => 'terminalperformance.store',
    'show' => 'terminalperformance.show'
]], ['except', [
    'edit', 'update', 'delete'
]])->middleware(['auth', 'ajax', 'reports']);

Route::resource('/home/reports/terminalalarms', 'TerminalAlarmReportController', ['names' => [
    'index' => 'terminalalarms.index',
    'create' => 'terminalalarms.create',
    'store' => 'terminalalarms.store',
    'show' => 'terminalalarms.show'
]], ['except', [
    'edit', 'update', 'delete'
]])->middleware(['auth', 'ajax', 'reports']);

Route::resource('/home/reports/driverperformance', 'DriverPerformanceReportController', ['names' => [
    'index' => 'driverperformance.index',
    'create' => 'driverperformance.create',
    'store' => 'driverperformance.store'
]], ['except', [
    'show','edit', 'update', 'delete'
]])->middleware(['auth', 'ajax', 'reports']);

Route::resource('/home/reports/driveralarms', 'DriverAlarmReportController', ['names' => [
    'index' => 'driveralarms.index',
    'create' => 'driveralarms.create',
    'store' => 'driveralarms.store'
]], ['except', [
    'show','edit', 'update', 'delete'
]])->middleware(['auth', 'ajax', 'reports']);

/*
|--------------------------------------------------------------------------
| Map Panel Routes
|--------------------------------------------------------------------------
| These routes manage access to the map panel. 
|  
*/

Route::get('/map', 'MapController@index')->name('map')->middleware(['auth','map']);

Route::resource('routerepeat', 'RouteRepeatController', ['only', [
    'create','store'
]])->middleware(['auth','map']);

Route::resource('routerepeat', 'RouteRepeatController', ['only', [
    'create','store'
]])->middleware(['auth','map']);

Route::resource('/map/statistics/performance', 'PerformanceMapController', ['names' => [
    'create' => 'mapperformance.create',
    'store' => 'mapperformance.store',
]], ['except', [
    'index','edit','show','update', 'delete'
]])->middleware(['auth', 'map', 'ajax']);

Route::resource('/map/statistics/terminalperformance', 'MapTerminalPerformanceController', ['names' => [
    'create' => 'terminalmapperformance.create',
    'store' => 'terminalmapperformance.store',
]], ['except', [
    'index','edit','show','update', 'delete'
]])->middleware(['auth', 'map', 'ajax']);

Route::resource('/map/statistics/terminalalarms', 'MapTerminalAlarmController', ['names' => [
    'create' => 'terminalmapalarms.create',
    'store' => 'terminalmapalarms.store',
]], ['except', [
    'index','edit','show','update', 'delete'
]])->middleware(['auth', 'map', 'ajax']);

Route::resource('/map/statistics/driverperformance', 'MapDriverPerformanceController', ['names' => [
    'create' => 'drivermapperformance.create',
    'store' => 'drivermapperformance.store',
]], ['except', [
    'index','edit','show','update', 'delete'
]])->middleware(['auth', 'map', 'ajax']);

Route::resource('/map/statistics/driveralarms', 'MapDriverAlarmController', ['names' => [
    'create' => 'drivermapalarms.create',
    'store' => 'drivermapalarms.store',
]], ['except', [
    'index','edit','show','update', 'delete'
]])->middleware(['auth', 'map', 'ajax']);

Route::get('commandterminal/{id}', 'CommandTerminalController@show')
    ->name('commandterminal.show')
    ->middleware(['auth', 'terminalControl', 'ajax']);

Route::post('commandterminal/{id}', 'CommandTerminalController@send')
    ->name('commandterminal.send')
    ->middleware(['auth', 'terminalControl', 'ajax']);

/*
|--------------------------------------------------------------------------
| Server Panel Routes
|--------------------------------------------------------------------------
| These routes manage access to the map panel. 
|  
*/

// Route::resource('tcpservers', 'TCPSocketServerController')->middleware('auth');

Route::resource('mapservers', 'MapSocketServerController')->middleware('auth');

Route::resource('apikeys', 'APIKeyController')->middleware('auth');

Route::get('serverlogs','ViewLogController@index')->name('serverlogs.index')->middleware('auth');

Route::get('serverlogs/other','ViewLogController@other')->name('serverlogs.other')->middleware('auth');

Route::post('serverlogs/show','ViewLogController@show')->name('serverlogs.show')->middleware('auth');   

resources/views/dashboard/admin.blade.php
@extends('layouts.partial')

@section('body')

<h2 class="text-center">Admin Control Panel</h2>

<div class="col-sm-3">

<button data-source="{{ route('users.index') }}" class="btn btn-dashboard btn-dashboard pull-left partial-button-embed" data-container="admin" style="margin-right: 3px;">
    <div class="mdi mdi-account mdi-48px"></div> Users
</button>

</div>

<div class="col-sm-3">

<button data-source="{{ route('roles.index') }}" class="btn btn-dashboard btn-dashboard-red pull-left partial-button-embed" data-container="admin" style="margin-right: 3px;">
    <div class="mdi mdi-account-multiple mdi-48px"></div> User groups
</button>

</div>

<div class="col-sm-3">

<button data-source="{{ route('permissions.index') }}" class="btn btn-dashboard btn-dashboard-green pull-left partial-button-embed" data-container="admin" style="margin-right: 3px;">
    <div class="mdi mdi-key-variant mdi-48px"></div> User permissions
</button>

</div>

<div class="col-sm-3">

<button data-source="{{ route('terminals.index') }}" class="btn btn-dashboard btn-dashboard-blue pull-left partial-button-embed" data-container="admin" style="margin-right: 3px;">
    <div class="mdi mdi-car mdi-48px"></div> Terminals
</button>

</div>

@endsection

@section('footer')
@include('components.flash')

<script>
    $(function(){
        $('.partial-button-embed').each(function(index) {
            $(this).click(function(e) {
                $('.active').removeClass();
                var link = $(this).data('source');
                $('a[href = "'+link+'"]').parent().addClass('active');
            });
        });
    });
</script>

@endsection

resources/views/dashboard/home.blade.php
@extends('layouts.partial')

@section('body')
    <div class="col-lg-9">

        <div class="panel panel-default">
            <div class="panel-heading">Links</div>
            <div class="panel-body">
                <div class="partial-container" id="homelinks" data-name="homelinks">
                    <div class="col-sm-3">
                        @can('Terminal Control')
                            <a href="{{ url('/terminalcontrol') }}" class="btn btn-dashboard btn-dashboard-aqua pull-left" style="margin-right: 3px;">
                                <div class="mdi mdi-map-marker-multiple mdi-48px"></div> Map
                            </a>
                        @endcan
                    </div>
                    <div class="col-sm-3">
                        <button data-source="{{ route('users.index') }}" class="btn btn-dashboard btn-dashboard-purple pull-left partial-button-embed" data-container="home" style="margin-right: 3px;">
                            <div class="mdi mdi-car mdi-48px"></div> Terminals
                        </button>
                    </div>
                        
                    <div class="col-sm-3">
                        <button data-source="{{ route('reports.index') }}" class="btn btn-dashboard btn-dashboard-blue pull-left partial-button-embed" data-container="home" style="margin-right: 3px;">
                            <div class="mdi mdi-clipboard-text mdi-48px"></div> Reports
                        </button>
                    </div>
                        
                    <div class="col-sm-3">
                        <a href="{{ route('myaccount.index') }}" class="btn btn-dashboard btn-dashboard-green pull-left" style="margin-right: 3px;">
                            <div class="mdi mdi-account mdi-48px"></div> My Account
                        </a>
                    </div>
                </div>
            </div>

        </div>

        @can('Access Admin Panel')
            <div class="panel panel-default">
                <div class="panel-heading">Admin</div>
                <div class="panel-body">
                    <div class="partial-container" id="homelinks" data-name="homelinks">
                        <div class="col-sm-3">
                            <a href="{{ url('/manageusers') }}" class="btn btn-dashboard btn-dashboard-aqua pull-left" style="margin-right: 3px;">
                                <div class="mdi mdi-account-key mdi-48px"></div> Admin
                            </a>
                        </div>
                        @can('Manage Server')
                            <div class="col-sm-3">
                                <button data-source="{{ route('users.index') }}" class="btn btn-dashboard btn-dashboard-purple pull-left partial-button-embed" data-container="home" style="margin-right: 3px;">
                                    <div class="mdi mdi-server mdi-48px"></div> Server
                                </button>
                            </div>
                        @endcan
                    </div>
                </div>

            </div>
        @endcan

    </div>

    <div class="col-lg-3">
        <div class="panel panel-default">
            <div class="panel-heading">Dashboard</div>
            <div class="panel-body">
                <h1>{{ $y }}</h1>
                <h4>{{ $md }}</h4>
                @if (session('status'))
                    <div class="alert alert-success">
                        {{ session('status') }}
                    </div>
                @endif
        
                You are logged in!
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">Recent Events</div>
            <div class="panel-body">
                @if (isset($data))
                    @foreach ($data as $entry)
                        <div>
                            <h4>{{$entry['age']}}</h4>
                            <h5>{{$entry['name']}}</h5>
                            <p>{{$entry['description']}}</p>
                            <p>{{$entry['date']}}</p>
                        </div>
                    @endforeach
                @else
                    <p>No recent events</p>
                @endif
            </div>
        </div>
    </div>

</div>

@endsection

@section('footer')
@include('components.flash')
<script>
    $(function(){
        $('.partial-button-embed').each(function(index) {
            $(this).click(function(e) {
                $('.active').removeClass();
                var link = $(this).data('source');
                $('a[href = "'+link+'"]').parent().addClass('active');
            });
        });
    });
</script>

@endsection

resources/views/dashboard/index.blade.php
@extends('layouts.manage')

@section('side-bar')

<button data-source="" class="btn btn-dashboard btn-dashboard pull-left partial-button-embed" data-container="terminalmanagement" style="margin-right: 3px;">
    <div class="mdi mdi-clipboard-text mdi-48px"></div> Overview
</button>

<button data-source="" class="btn btn-dashboard btn-dashboard-red pull-left partial-button-embed" data-container="terminalmanagement" style="margin-right: 3px;">
    <div class="mdi mdi-speedometer mdi-48px"></div> Performance
</button>

<button data-source="" class="btn btn-dashboard btn-dashboard-green pull-left partial-button-embed" data-container="terminalmanagement" style="margin-right: 3px;">
    <div class="mdi mdi-map-marker-radius mdi-48px"></div> Location data
</button>

<button data-source="" class="btn btn-dashboard btn-dashboard-blue pull-left partial-button-embed" data-container="terminalmanagement" style="margin-right: 3px;">
    <div class="mdi mdi-alert mdi-48px"></div> Alerts
</button>

@endsection

@section('body')

<div class="partial-container" id="terminalmanagement" data-name="terminalmanagement">
    <div class="--auto-load" data-source="" data-container="terminalmanagement" data-state="ready"></div>
</div>

@endsection

@section('footer')
@include('components.flash')    

<script>
    $('.partial-container').each(function(index){
        $(this).partialLoader('container');
    });
    $('.partial-link').each(function(index){            
        $(this).partialLoader('link');
    });
    $('.auto-load').each(function(index) {        
        $(this).partialLoader('autoload');
    });
    $('.partial-button').each(function(index) {        
        $(this).partialLoader('button');
    });
</script>

@endsection

resources/views/dashboard/reports.blade.php
@extends('layouts.partial')

@section('header')
<div class="navbar partial-navbar">
    <div class="container-fluid">
      <div class="navbar-header">
        <span class="navbar-brand">Reports</span>
      </div>
      <ul class="nav navbar-nav partial-nav">
        <li class="active"><a class="partial-link-embed" data-container="reports" href="{{ url('terminalreports') }}">Terminal stats</a></li>
        <li><a class="partial-link-embed" data-container="reports" href="#">Terminal events</a></li>
        <li><a class="partial-link-embed" data-container="reports" href="#">Driver stats</a></li>
        <li><a class="partial-link-embed" data-container="reports" href="#">Driver events</a></li>
      </ul>
    </div>
</div>
@endsection

@section('body')
<div class="partial-container" id="reports" data-name="reports">
    <div class="auto-load-embed" data-source="{{ url('terminalreports') }}" data-container="reports" data-state="ready"></div>
</div>
@endsection

@section('footer')

@yield('footer')
@include('components.flash')

<script>            
    $(init)
    function init() {
        $('.partial-navbar a').each(function (index, element) {
            var element = this;
            $(element).on('click',function (e) {
                $('.partial-nav li.active').removeClass('active');
                $(element).parent().addClass('active');
            });
        });
        $('.partial-container').each(function(index){
            $(this).partialLoader('container');
        });
    }
</script>

@endsection