routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/verifyemail/{token}', 'Auth\RegisterController@verify');


Route::get('fire', function () {
    // this fires the event
    event(new App\Events\MapAccess());
    return "event fired";
});

Route::get('test', function () {
    // this checks for the event
    return view('test');
});

/*
|--------------------------------------------------------------------------
| Admin Panel Routes
|--------------------------------------------------------------------------
| These routes manage access to the admin panel. 
|  
*/

Route::get('/admin', 'AdminPanelController@index')->name('admin')->middleware(['auth', 'admin']);

Route::get('/admin/dashboard', 'AdminPanelController@dashboard')->name('admin.dashboard')->middleware(['auth', 'ajax', 'admin']);

Route::resource('users', 'UserController', ['except', [
    'show'
]])->middleware(['auth', 'ajax', 'admin', 'manageUsers']);

Route::resource('roles', 'RoleController', ['except', [
    'show'
]])->middleware(['auth', 'ajax', 'admin', 'manageUsers']);

Route::resource('permissions', 'PermissionController', ['except', [
    'show'
]])->middleware(['auth', 'ajax', 'admin', 'manageUsers']);

Route::resource('terminals', 'TerminalController', ['except', [
    'show'
]])->middleware(['auth', 'ajax', 'admin', 'terminalAdmin']);

Route::get('terminals/edituser/{id}', 'TerminalController@editUser')->name('terminals.editUser')->middleware(['auth', 'ajax']);

Route::post('terminals/updateuser/{id}', 'TerminalController@updateUser')->name('terminals.updateUser')->middleware(['auth', 'ajax']);

Route::resource('terminalconfigs', 'TerminalConfigurationController')->middleware(['auth', 'ajax']);


/*
|--------------------------------------------------------------------------
| My Account Panel Routes
|--------------------------------------------------------------------------
| These routes manage access to the my account panel. 
|  
*/

Route::resource('myaccount', 'MyAccountController', ['only', [
    'index','create', 'store'
]])->middleware(['auth', 'ajax']);

/*
|--------------------------------------------------------------------------
| Home Panel Routes
|--------------------------------------------------------------------------
| These routes manage access to the home panel. 
|  
*/

Route::get('/home', 'HomeController@index')->name('home')->middleware(['auth']);

Route::get('/home/dashboard', 'HomeController@dashboard')->name('home.dashboard')->middleware(['auth', 'ajax', 'admin']);


Route::resource('userterminals', 'UserTerminalsController', ['only', [
    'index','edit','update'
]])->middleware(['auth', 'ajax', 'terminalManage']);

Route::resource('terminalgroups', 'TerminalGroupController', ['except', [
    'show'
]])->middleware(['auth', 'ajax', 'terminalManage']);

Route::resource('drivers', 'DriverController', ['except', [
    'show'
]]);


/**
 * Reports subsection routes
 * This is meant for the reports subsection of home
 */

Route::get('/home/reports', 'ReportController@index')->name('reports')->middleware(['auth','reports']);

Route::get('/home/reports/dashboard', 'ReportController@dashboard')->name('reports.dashboard')->middleware(['auth', 'ajax', 'reports']);

Route::post('home/reports/export', 'ReportController@export')->name('exportreport')->middleware(['auth', 'reports']);

Route::resource('/home/reports/terminalperformance', 'TerminalPerformanceReportController', ['names' => [
    'index' => 'terminalperformance.index',
    'create' => 'terminalperformance.create',
    'store' => 'terminalperformance.store',
    'show' => 'terminalperformance.show'
]], ['except', [
    'edit', 'update', 'delete'
]])->middleware(['auth', 'ajax', 'reports']);

Route::resource('/home/reports/terminalalarms', 'TerminalAlarmReportController', ['names' => [
    'index' => 'terminalalarms.index',
    'create' => 'terminalalarms.create',
    'store' => 'terminalalarms.store',
    'show' => 'terminalalarms.show'
]], ['except', [
    'edit', 'update', 'delete'
]])->middleware(['auth', 'ajax', 'reports']);

Route::resource('/home/reports/driverperformance', 'DriverPerformanceReportController', ['names' => [
    'index' => 'driverperformance.index',
    'create' => 'driverperformance.create',
    'store' => 'driverperformance.store'
]], ['except', [
    'show','edit', 'update', 'delete'
]])->middleware(['auth', 'ajax', 'reports']);

Route::resource('/home/reports/driveralarms', 'DriverAlarmReportController', ['names' => [
    'index' => 'driveralarms.index',
    'create' => 'driveralarms.create',
    'store' => 'driveralarms.store'
]], ['except', [
    'show','edit', 'update', 'delete'
]])->middleware(['auth', 'ajax', 'reports']);

/*
|--------------------------------------------------------------------------
| Map Panel Routes
|--------------------------------------------------------------------------
| These routes manage access to the map panel. 
|  
*/

Route::get('/map', 'MapController@index')->name('map')->middleware(['auth','map']);

Route::resource('routerepeat', 'RouteRepeatController', ['only', [
    'create','store'
]])->middleware(['auth','map']);

Route::resource('routerepeat', 'RouteRepeatController', ['only', [
    'create','store'
]])->middleware(['auth','map']);

Route::resource('/map/statistics/performance', 'PerformanceMapController', ['names' => [
    'create' => 'mapperformance.create',
    'store' => 'mapperformance.store',
]], ['except', [
    'index','edit','show','update', 'delete'
]])->middleware(['auth', 'map', 'ajax']);

Route::resource('/map/statistics/terminalperformance', 'MapTerminalPerformanceController', ['names' => [
    'create' => 'terminalmapperformance.create',
    'store' => 'terminalmapperformance.store',
]], ['except', [
    'index','edit','show','update', 'delete'
]])->middleware(['auth', 'map', 'ajax']);

Route::resource('/map/statistics/terminalalarms', 'MapTerminalAlarmController', ['names' => [
    'create' => 'terminalmapalarms.create',
    'store' => 'terminalmapalarms.store',
]], ['except', [
    'index','edit','show','update', 'delete'
]])->middleware(['auth', 'map', 'ajax']);

Route::resource('/map/statistics/driverperformance', 'MapDriverPerformanceController', ['names' => [
    'create' => 'drivermapperformance.create',
    'store' => 'drivermapperformance.store',
]], ['except', [
    'index','edit','show','update', 'delete'
]])->middleware(['auth', 'map', 'ajax']);

Route::resource('/map/statistics/driveralarms', 'MapDriverAlarmController', ['names' => [
    'create' => 'drivermapalarms.create',
    'store' => 'drivermapalarms.store',
]], ['except', [
    'index','edit','show','update', 'delete'
]])->middleware(['auth', 'map', 'ajax']);

Route::get('commandterminal/{id}', 'CommandTerminalController@show')
    ->name('commandterminal.show')
    ->middleware(['auth', 'terminalControl', 'ajax']);

Route::post('commandterminal/{id}', 'CommandTerminalController@send')
    ->name('commandterminal.send')
    ->middleware(['auth', 'terminalControl', 'ajax']);

/*
|--------------------------------------------------------------------------
| Server Panel Routes
|--------------------------------------------------------------------------
| These routes manage access to the map panel. 
|  
*/

// Route::resource('tcpservers', 'TCPSocketServerController')->middleware('auth');

Route::resource('mapservers', 'MapSocketServerController')->middleware('auth');

Route::resource('apikeys', 'APIKeyController')->middleware('auth');

Route::get('serverlogs','ViewLogController@index')->name('serverlogs.index')->middleware('auth');

Route::get('serverlogs/other','ViewLogController@other')->name('serverlogs.other')->middleware('auth');

Route::post('serverlogs/show','ViewLogController@show')->name('serverlogs.show')->middleware('auth');   

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;
use App\Terminal;

class User extends Authenticatable
{
    use Notifiable;
    use HasROles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'middle_last_name', 'email', 'phone', 'password','email_token'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token', 'verified', 'email_token'
    ];    

    public function setPasswordAttribute($password)
    {   
        $this->attributes['password'] = bcrypt($password);
    }

    public function getUsernameAttribute()
    {
        return $this->first_name." ".$this->middle_last_name;
    }

    public function getAdminTerminalsAttribute()
    {
        $terminals;
        if ($this->hasPermissionTo('Terminal Control - All Terminals')) {
            $terminals = Terminal::all();
        }
        else if ($this->hasPermissionTo('Terminal Control')) {
            $terminals = $this->terminals;
        }
        
        return $terminals;
    }

    public function terminals() 
    {
        return $this->hasMany('App\Terminal','client_id');
    }

    public function terminal_groups()
    {
        return $this->hasMany('App\TerminalGroup','user_id');
    }

    public function terminal_config_logs() 
    {
        return $this->hasMany('App\TerminalConfigLog','user_id');
    }

    public function terminal_access_logs() 
    {
        return $this->hasMany('App\TerminalAccessLog','user_id');
    }

    public function owns_terminal($terminal)
    {
        return $this->terminals->contains($terminal);
    }

    public function drivers() 
    {
        return $this->hasMany('App\Driver','owner_id');
    }

    public function map_auth_keys()
    {
        return $this->hasMany('App\MapAuthKey','user_id');
    }
}

resources/views/manageusers/createpermission.blade.php
@extends('layouts.partial')

@section('header')
    <h2>Create permission</h2>    
    <p>Create a new permission</p>    
    @if (count($errors) > 0)
        <p class="text-danger" >It seems there were errors in the input</p>
    @endif
@endsection

@section('body')

    {{ Form::open(array('url' => 'permissions', 'class' => 'partial-form-embed', 'data-container' => 'admin')) }}

    <div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
        {{ Form::label('name', 'Name') }}
        {{ Form::text('name', '', array('class' => 'form-control')) }}
        @if ($errors->has('name'))
            <span class="help-block">
                <strong>{{ $errors->first('name') }}</strong>
            </span>
        @endif
    </div>
    <div>
    @if(!$roles->isEmpty())
        <h4>Assign Permission to User <Group></Group>s</h4>

        @foreach ($roles as $role) 
            {{ Form::checkbox('roles[]',  $role->id ) }}
            {{ Form::label($role->name, ucfirst($role->name)) }}<br>

        @endforeach
    @endif
    </div>
    
    <div class="form-group">
        <button data-source="{{ route('permissions.index') }}" class="btn btn-red pull-left partial-button-embed" data-container="admin" style="margin-right: 3px;">
            <i class="mdi mdi-close mdi-18px"></i> Cancel
        </button>
    
        <button type="submit" class="btn btn-aqua">
            <i class="mdi mdi-upload mdi-18px"></i> Submit
        </button>
    </div>

    {{ Form::close() }}
@endsection

resources/views/manageusers/createrole.blade.php
@extends('layouts.partial')

@section('header')
    <h2>Create user group</h2>    
    <p>Create a new user group</p>    
    @if (count($errors) > 0)
        <p class="text-danger" >It seems there were errors in the input</p>
    @endif
@endsection

@section('body')
    
    {{ Form::open(array('url' => 'roles', 'class' => 'partial-form-embed', 'data-container' => 'admin')) }}

    <div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
        {{ Form::label('name', 'Name') }}
        {{ Form::text('name', null, array('class' => 'form-control')) }}
        @if ($errors->has('name'))
            <span class="help-block">
                <strong>{{ $errors->first('name') }}</strong>
            </span>
        @endif
    </div>

    <h5><b>Assign Permissions</b></h5>

    <div class="form-group {{ $errors->has('permissions') ? ' has-error' : '' }}">
        @foreach ($permissions as $permission)
            {{ Form::checkbox('permissions[]',  $permission->id ) }}
            {{ Form::label($permission->name, ucfirst($permission->name)) }}<br>
        @endforeach
        @if ($errors->has('permissions'))
            <span class="help-block">
                <strong>{{ $errors->first('permissions') }}</strong>
            </span>
        @endif
    </div>

    <div class="form-group">
        <button data-source="{{ route('roles.index') }}" class="btn btn-red pull-left partial-button-embed" data-container="admin" style="margin-right: 3px;">
            <i class="mdi mdi-close mdi-18px"></i> Cancel
        </button>
    
        <button type="submit" class="btn btn-aqua">
            <i class="mdi mdi-upload mdi-18px"></i> Submit
        </button>
    </div>

    {{ Form::close() }}

@endsection

resources/views/manageusers/createuser.blade.php
@extends('layouts.partial')

@section('header')
    <h2>Add user</h2>    
    <p>Add a new user to the system</p>    
    @if (count($errors) > 0)
        <p class="text-danger" >It seems there were errors in the input</p>
    @endif
@endsection

@section('body')

    {{ Form::open(array('url' => 'users', 'class' => 'partial-form-embed', 'data-container' => 'admin')) }}

    <div class="form-group {{ $errors->has('first_name') ? ' has-error' : '' }}">
        {{ Form::label('first_name', 'First Name *') }}
        {{ Form::text('first_name', '', array('class' => 'form-control', 'required', 'placeholder' => 'First Name')) }}
        @if ($errors->has('first_name'))
            <span class="help-block">
                <strong>{{ $errors->first('first_name') }}</strong>
            </span>
        @endif
    </div>

    <div class="form-group {{ $errors->has('middle_last_name') ? ' has-error' : '' }}">
        {{ Form::label('middle_last_name', 'Middle, Last Name *') }}
        {{ Form::text('middle_last_name', '', array('class' => 'form-control', 'required', 'placeholder' => 'Middle, Last Name')) }}
        @if ($errors->has('middle_last_name'))
            <span class="help-block">
                <strong>{{ $errors->first('middle_last_name') }}</strong>
            </span>
        @endif
    </div>

    <div class="form-group {{ $errors->has('email') ? ' has-error' : '' }}">
        {{ Form::label('email', 'Email *') }}
        {{ Form::email('email', '', array('class' => 'form-control', 'required','placeholder' => 'someone@example.com')) }}
        @if ($errors->has('email'))
            <span class="help-block">
                <strong>{{ $errors->first('email') }}</strong>
            </span>
        @endif
    </div>

    <div class="form-group {{ $errors->has('phone') ? ' has-error' : '' }}">
        {{ Form::label('phone', 'Phone *') }}
        {{ Form::text('phone', '', array('class' => 'form-control', 'required' , 'placeholder' => '254700000000')) }}
        @if ($errors->has('phone'))
            <span class="help-block">
                <strong>{{ $errors->first('phone') }}</strong>
            </span>
        @endif
    </div>

    <div class="form-group {{ $errors->has('roles') ? ' has-error' : '' }}">
        {{ Form::label('roles', 'User group (Optional)') }}<br>
        @foreach ($roles as $role)
            {{ Form::checkbox('roles[]',  $role->id ) }}
            {{ Form::label($role->name, ucfirst($role->name)) }}<br>
        @endforeach
        @if ($errors->has('roles'))
            <span class="help-block">
                <strong>{{ $errors->first('roles') }}</strong>
            </span>
        @endif
    </div>

    <div class="form-group {{ $errors->has('password') ? ' has-error' : '' }}">
        {{ Form::label('password', 'Password *') }}<br>
        {{ Form::password('password', array('class' => 'form-control', 'required', 'placeholder' => 'Type a password here')) }}
        @if ($errors->has('password'))
            <span class="help-block">
                <strong>{{ $errors->first('password') }}</strong>
            </span>
        @endif
    </div>

    <div class="form-group">
        {{ Form::label('password', 'Confirm Password *') }}<br>
        {{ Form::password('password_confirmation', array('class' => 'form-control', 'required', 'placeholder' => 'Retype password here to confirm')) }}

    </div>

    <div class="form-group">
        <button data-source="{{ route('users.index') }}" class="btn btn-red pull-left partial-button-embed" data-container="admin" style="margin-right: 3px;">
            <i class="mdi mdi-close mdi-18px"></i> Cancel
        </button>
    
        <button type="submit" class="btn btn-aqua">
            <i class="mdi mdi-upload mdi-18px"></i> Submit
        </button>
    </div>

    {{ Form::close() }}    
@endsection

resources/views/manageusers/editpermission.blade.php
@extends('layouts.partial')

@section('header')
    <h2>Edit permission</h2>
    <h4>{{ $permission->name }}</h4>
    <p>Change user permission details</p>
    <p class="text-danger" ><strong>CAUTION!!</strong> Renaming some user groups could break the application</p>
    @if (count($errors) > 0)
        <p class="text-danger" >It seems there were errors in the input</p>
    @endif
@endsection

@section('body')
    {{ Form::model($permission, array('route' => array('permissions.update', $permission->id), 'method' => 'PUT', 'class' => 'partial-form-embed', 'data-container' => 'admin')) }}{{-- Form model binding to automatically populate our fields with permission data --}}

    <div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
        {{ Form::label('name', 'Permission Name') }}
        {{ Form::text('name', null, array('class' => 'form-control')) }}
        @if ($errors->has('name'))
            <span class="help-block">
                <strong>{{ $errors->first('name') }}</strong>
            </span>
        @endif
    </div>
    <div class="form-group">
        <button data-source="{{ route('permissions.index') }}" class="btn btn-red pull-left partial-button-embed" data-container="admin" style="margin-right: 3px;">
            <i class="mdi mdi-close mdi-18px"></i> Cancel
        </button>
    
        <button type="submit" class="btn btn-aqua">
            <i class="mdi mdi-upload mdi-18px"></i> Submit
        </button>
    </div>

    {{ Form::close() }}    
@endsection

resources/views/manageusers/editrole.blade.php
@extends('layouts.partial')

@section('header')
    <h2>Edit user group</h2>
    <h4>{{ $role->name }}</h4>
    <p>Change user permission details</p>
    <p class="text-danger" ><strong>CAUTION!!</strong> Renaming some user groups could break the application</p>
    @if (count($errors) > 0)
        <p class="text-danger" >It seems there were errors in the input</p>
    @endif
@endsection

@section('body')
    {{ Form::model($role, array('route' => array('roles.update', $role->id), 'method' => 'PUT', 'class' => 'partial-form-embed', 'data-container' => 'admin')) }}

    <div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
        {{ Form::label('name', 'Role Name') }}
        {{ Form::text('name', null, array('class' => 'form-control')) }}
        @if ($errors->has('name'))
            <span class="help-block">
                <strong>{{ $errors->first('name') }}</strong>
            </span>
        @endif
    </div>

    <h5><b>Assign Permissions</b></h5>

    <div class="form-group {{ $errors->has('permissions') ? ' has-error' : '' }}">
        @foreach ($permissions as $permission)
            {{Form::checkbox('permissions[]',  $permission->id, $role->permissions ) }}
            {{Form::label($permission->name, ucfirst($permission->name)) }}<br>
        @endforeach
        @if ($errors->has('permissions'))
            <span class="help-block">
                <strong>{{ $errors->first('permissions') }}</strong>
            </span>
        @endif
    </div>
    
    <div class="form-group">
        <button data-source="{{ route('roles.index') }}" class="btn btn-red pull-left partial-button-embed" data-container="admin" style="margin-right: 3px;">
            <i class="mdi mdi-close mdi-18px"></i> Cancel
        </button>
    
        <button type="submit" class="btn btn-aqua">
            <i class="mdi mdi-upload mdi-18px"></i> Submit
        </button>
    </div>

    {{ Form::close() }}    
@endsection

resources/views/manageusers/edituser.blade.php
@extends('layouts.partial')

@section('header')
    <h2>Edit user</h2>
    <h4>{{ $user->username }}</h4>
    <p>Change user details</p>    
    @if (count($errors) > 0)
        <p class="text-danger" >It seems there were errors in the input</p>
    @endif
@endsection

@section('body')

    {{ Form::model($user, array('route' => array('users.update', $user->id), 'method' => 'PUT', 'class' => 'partial-form-embed', 'data-container' => 'admin')) }}{{-- Form model binding to automatically populate our fields with user data --}}

    <div class="form-group {{ $errors->has('first_name') ? ' has-error' : '' }}">
        {{ Form::label('first_name', 'First Name') }} <span>: {{$user->first_name}}</span>
        {{ Form::text('first_name', '', array('class' => 'form-control', 'placeholder' => 'New first name')) }}
        @if ($errors->has('first_name'))
            <span class="help-block">
                <strong>{{ $errors->first('first_name') }}</strong>
            </span>
        @endif
    </div>

    <div class="form-group {{ $errors->has('middle_last_name') ? ' has-error' : '' }}">
        {{ Form::label('middle_last_name', 'Middle, Last Name') }} <span>: {{$user->middle_last_name}}</span>
        {{ Form::text('middle_last_name', '', array('class' => 'form-control', 'placeholder' => 'New middle, last name')) }}
        @if ($errors->has('middle_last_name'))
            <span class="help-block">
                <strong>{{ $errors->first('middle_last_name') }}</strong>
            </span>
        @endif
    </div>

    <div class="form-group {{ $errors->has('email') ? ' has-error' : '' }}">
        {{ Form::label('email', 'Email') }} <span>: {{$user->email}}</span>
        {{ Form::email('email', '', array('class' => 'form-control', 'placeholder' => 'New email')) }}
        @if ($errors->has('email'))
            <span class="help-block">
                <strong>{{ $errors->first('email') }}</strong>
            </span>
        @endif
    </div>

    <div class="form-group {{ $errors->has('phone') ? ' has-error' : '' }}">
        {{ Form::label('phone', 'Phone') }} <span>: {{$user->phone}}</span>
        {{ Form::text('phone', '', array('class' => 'form-control', 'placeholder' => 'New phone number')) }}
        @if ($errors->has('phone'))
            <span class="help-block">
                <strong>{{ $errors->first('phone') }}</strong>
            </span>
        @endif
    </div>

    <h5><b>Assign to group</b></h5>

    <div class='form-group'>
        @foreach ($roles as $role)
            {{ Form::checkbox('roles[]',  $role->id, $user->roles ) }}
            {{ Form::label($role->name, ucfirst($role->name)) }}<br>

        @endforeach
    </div>

    <div class="form-group">
        {{ Form::label('password', 'Password') }}<br>
        {{ Form::password('password', array('class' => 'form-control','placeholder' => 'New password')) }}
        @if ($errors->has('password'))
            <span class="help-block">
                <strong>{{ $errors->first('password') }}</strong>
            </span>
        @endif

    </div>

    <div class="form-group {{ $errors->has('password') ? ' has-error' : '' }}">
        {{ Form::label('password', 'Confirm Password') }}<br>
        {{ Form::password('password_confirmation', array('class' => 'form-control','placeholder' => 'New password confirmation')) }}

    </div>

    <div class="form-group">
        <button data-source="{{ route('users.index') }}" class="btn btn-red pull-left partial-button-embed" data-container="admin" style="margin-right: 3px;">
            <i class="mdi mdi-close mdi-18px"></i> Cancel
        </button>
    
        <button type="submit" class="btn btn-aqua">
            <i class="mdi mdi-upload mdi-18px"></i> Submit
        </button>
    </div>

    {{ Form::close() }}    

@endsection

resources/views/manageusers/index.blade.php
@extends('layouts.manage')

@section('side-bar')

<li class="active"><a class="partial-link" data-container="admin" href="{{ route('dashboard.admin') }}">Dashboard</a></li>
@can('Manage Users')
    <li><a class="partial-link" data-container="admin" href="{{ route('users.index') }}">Users</a></li>
@endcan
@can('Administer roles and permissions')
    <li><a class="partial-link" data-container="admin" href="{{ route('roles.index') }}">User groups</a></li>
    <li><a class="partial-link" data-container="admin" href="{{ route('permissions.index') }}">User permissions</a></li>
@endcan

@can('Manage Terminals - Admin')
    <li><a class="partial-link" data-container="admin" href="{{ route('terminals.index') }}">Terminals</a></li>
    <li><a class="partial-link" data-container="admin" href="{{ route('terminalconfigs.index') }}">Terminal COnfigurations</a></li>
@endcan

@endsection

@section('body')    
<div class="partial-container" id="admin" data-name="admin">
    <div class="auto-load" data-source="{{ route('dashboard.admin') }}" data-container="admin" data-state="ready"></div>
</div>
@endsection

@section('footer')
    <script>
        $('.partial-container').each(function(index){
            $(this).partialLoader('container');
        });
        $('.partial-link').each(function(index){            
            $(this).partialLoader('link');
        });
        $('.auto-load').each(function(index) {        
            $(this).partialLoader('autoload');
        });
    </script>
@endsection

resources/views/manageusers/indexpermissions.blade.php
@extends('layouts.partial')

@section('header')
    <h2>Manage Permissions</h2>
    <p>Create, edit and remove user permissions from the system for access control</p>
@endsection

@section('body')
    <div class="table-responsive">
        <table class="table table-bordered table-striped data-table-embed" width="100%">
            <thead>
                <tr>
                    <th>Permissions</th>
                    <th>Operation</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($permissions as $permission)
                <tr>
                    <td>{{ $permission->name }}</td> 
                    <td>
                    <a href="{{ URL::to('permissions/'.$permission->id.'/edit') }}" class="btn btn-blue pull-left partial-link-embed" data-container="admin" style="margin-right: 3px;">Edit</a>
    
                    {!! Form::open(['method' => 'DELETE', 'route' => ['permissions.destroy', $permission->id], 'class' => 'partial-form-embed', 'data-container' => 'admin' ]) !!}
                    {!! Form::submit('Delete', ['class' => 'btn btn-red']) !!}
                    {!! Form::close() !!}
    
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        <a href="{{ URL::to('permissions/create') }}" class="btn btn-green partial-link-embed" data-container="admin">Add Permission</a>
    </div>    
@endsection

@section('footer')
    @include('components.embeddedtable')
@endsection

resources/views/manageusers/indexusers.blade.php
@extends('layouts.partial')

@section('header')
    <h2>Manage Users</h2>
    <p>Add, edit, remove and set user groups for users in the system</p>
@endsection

@section('body')
    <div class="table-responsive">    
        <table class="table table-bordered table-striped data-table-embed" width="100%">
            <colgroup>
                <col width="15%">
                <col width="30%">
                <col width="20%">
                <col width="15%">
                <col width="20%">
            </colgroup>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Contacts</th>
                    <th>Date/Time Added</th>
                    <th>Group memberships</th>
                    <th>Operations</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th>Name</th>
                    <th>Contacts</th>
                    <th>Date/Time Added</th>
                    <th>Group memberships</th>
                    <th>Operations</th>
                </tr>
            </tfoot>
    
            <tbody>
                @foreach ($users as $user)
                <tr>
    
                    <td>{{ $user->username }}</td>
                    <td>
                        <b>E-mail: </b>{{ $user->email }}
                        <br>
                        <b>Phone: </b>{{ $user->phone }}
                    </td>
                    <td>{{ $user->created_at->format('F d, Y h:ia') }}</td>
                    <td>
                        <ul>
                            @foreach ($user->roles as $role)
                                <li>{{ $role->name }}</li>
                            @endforeach
                        </ul>
                    </td>
                    <td>
                    <a href="{{ route('users.edit', $user->id) }}" class="btn btn-blue pull-left partial-link-embed" data-container="admin" style="margin-right: 3px;">Edit</a>
    
                    {!! Form::open(['method' => 'DELETE', 'route' => ['users.destroy', $user->id], 'class' => 'partial-form-embed', 'data-container' => 'admin' ]) !!}
                    {!! Form::submit('Delete', ['class' => 'btn btn-red']) !!}
                    {!! Form::close() !!}
    
                    </td>
                </tr>
                @endforeach
            </tbody>
    
        </table>
        <a id="btn-adduser" href="{{ route('users.create') }}" class="btn btn-green partial-link-embed" data-container="admin">Add User</a>
    </div>    
@endsection

@section('footer')
    @include('components.embeddedtable')
@endsection